/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    scala
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
   
   	/* module 2.1 -- Vert.x */
    val vertxVer = "4.5.11"
    implementation("io.vertx:vertx-core:$vertxVer")
    implementation("io.vertx:vertx-web:$vertxVer")
    implementation("io.vertx:vertx-web-client:$vertxVer")
       
    /* module 2.2 -- RxJava */
    implementation("io.reactivex.rxjava3:rxjava:3.1.8")

    /* module 3.1 - actors - akka*/
    implementation(platform("com.typesafe.akka:akka-bom_2.13:2.8.2"))
    implementation("com.typesafe.akka:akka-actor-typed_2.13")
    testImplementation("com.typesafe.akka:akka-actor-testkit-typed_2.13")

    /* module 4.2 */
    implementation("com.rabbitmq:amqp-client:5.24.0")

    // https://mvnrepository.com/artifact/org.jsoup/jsoup
    implementation("org.jsoup:jsoup:1.18.3")

    /* for single assignment */
    implementation("org.apache.pdfbox:pdfbox:2.0.29")
    implementation("org.apache.pdfbox:preflight:2.0.29")

    /* logging framework SLF4J */
    implementation("org.slf4j:slf4j-api:2.0.7")
    // testImplementation "org.slf4j:slf4j-reload4j:2.0.7"
    implementation("org.slf4j:slf4j-simple:2.0.7")

    implementation("org.scala-lang:scala3-library_3:3.6.2")
    testImplementation("org.scalatest:scalatest_3:3.2.19")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

sourceSets {
    main {
        scala {
            setSrcDirs(listOf("src/main/scala", "src/main/java"))
        }
        java {
            setSrcDirs(listOf<String>())
        }
    }
}